[package]
name = "ninja-linter"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
shadow-rs = "1.5.0"


[build-dependencies]
shadow-rs = "1.5.0"