[package]
name = "ninja-linter"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
shadow-rs = { version = "1.5.0", default-features = false }


[build-dependencies]
shadow-rs = "1.5.0"

[[bin]]
name = "ninja-linter"
path = "src/main.rs"
