name: Release ninja-linter

on:
  push:
    branches:
      - main
#    tags:
#      - "v*.*.*" TODO: Enable release workflow when testing is ready

# TODO: Re-enable release workflow when testing is ready job of down this.
#jobs:
#  build-and-release:
#    name: Build and release binaries
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        target:
#          - x86_64-unknown-linux-gnu
#          - x86_64-apple-darwin
#          - aarch64-apple-darwin
#          - x86_64-pc-windows-msvc
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Install Rust toolchain
#        uses: dtolnay/rust-toolchain@stable
#        with:
#          targets: ${{ matrix.target }}
#
#      - name: Build binary
#        run: cargo build --release --target ${{ matrix.target }}
#
#      - name: Prepare binary
#        shell: bash
#        run: |
#          BIN_NAME="ninja-linter"
#          TARGET="${{ matrix.target }}"
#          OUT_DIR="dist"
#          mkdir -p $OUT_DIR
#
#          if [[ "$TARGET" == *"windows"* ]]; then
#            cp target/$TARGET/release/$BIN_NAME.exe $OUT_DIR/$BIN_NAME-$TARGET.exe
#          else
#            cp target/$TARGET/release/$BIN_NAME $OUT_DIR/$BIN_NAME-$TARGET
#          fi
#
#      - name: Upload release assets
#        uses: softprops/action-gh-release@v2
#        with:
#          files: dist/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary
        shell: bash
        run: |
          BIN="ninja-linter"
          TARGET="${{ matrix.target }}"
          mkdir -p dist

          if [[ "$TARGET" == *"windows"* ]]; then
            cp target/$TARGET/release/$BIN.exe dist/$BIN-$TARGET.exe
          else
            cp target/$TARGET/release/$BIN dist/$BIN-$TARGET
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: ninja-linter-${{ matrix.target }}
          path: dist/*
